metadata:
    website_name: 'My Awesome Wiki'
    admin_email: 'admin@example.com'

secret_key: 'blah'
allow_registration: True
template_dir: 'templates'
site_root: '_site'
valid_extensions:
    - '.md'
debug: True

